### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager

### ISSUE THREAD

**Issue by k3j123** [fishwjy/MultiType-FilePicker#26]
I get this error when I try to open Imagepicker

**Comment by fishwjy** [comment]
Upgrade to Glide 4. Please try version 1.0.7.

**Comment by rushdroid** [comment]
This error is still not resolved in 1.0.8 version, It's keep crashing on my side. @k3j123 @fishwjy

**Comment by BilalSiddiqui** [comment]
You are facing this error because either you are using glide new version in your project or some library internally using newer version. When Gradle builds your project, It uses a newer version of Gradle. You can confirm this in External libraries of project in android studio. Use same version of glide will solve this problem.
